version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: lab6_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      - php

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    depends_on:
      - redis
      - elasticsearch
      - clickhouse

  redis:
    image: redis:7-alpine
    container_name: lab6_redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: lab6_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: lab6_clickhouse
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1